### ISSUE TITLE
[solved]setup.sh  fails -  building wheels for lxml fails with error

### ISSUE THREAD

**Issue by reklawykSekuL** [olzeug/Snips-Chefkoch#1]
trying to setup the Chefkoch-skill   on my respeaker core v2 but the setup fails when building wheels for lxml -  some dev versions are missing
[Chefkoch-skill-log.txt](https://github.com/olzeug/Snips-Chefkoch/files/3854101/Chefkoch-skill-log.txt)
how can this issue be fixed?
why do we need those dev-libs ? 

ok i found   this using google: [Github](https://github.com/mailpile/Mailpile/issues/1086)
after installing the missing dev libs  the setup.sh  finished without error but
building the wheel  for lxml takes about 30 minutes - so be patient while compiling happens in background.
Maybe this should  mentioned in the Read.me 
 
best regards
Luke

**Comment by olzeug** [comment]
I have included a warning.
